#!/bin/bash
# CTMS OTel agent installer — run ON the target node with sudo.
# Native systemd method from OTEL_ONBOARDING.md §3 Method 1, packaged as one
# command for the fleet rollout:
#
#   sudo bash install-otel-agent.sh <server-name> [role] [port]
#
#   server-name  REQUIRED, must match the node's label in targets/otel-hosts.yml
#                on Server 5 (e.g. node-03)
#   role         default: unassigned
#   port         default: 8889  (use 8890 on node-19..22 — linkx owns 8889 there)
#
# After install, Server 5's Prometheus picks the node up automatically (target
# already exists); allow the scrape through the local firewall (§6):
#   UFW hosts:    sudo ufw allow from 172.27.23.36 to any port <port> proto tcp
#   Docker hosts: sudo iptables -I DOCKER-USER -p tcp --dport <port> -s 172.27.23.36 -j ACCEPT
set -euo pipefail

SERVER_NAME="${1:?usage: sudo bash install-otel-agent.sh <server-name> [role] [port]}"
ROLE="${2:-unassigned}"
PORT="${3:-8889}"
OTEL_VERSION=0.157.0
MONITORING_IP=172.27.23.36
TRACE_ENDPOINT=172.27.23.213:4317

[ "$(id -u)" -eq 0 ] || { echo "run with sudo" >&2; exit 1; }

echo "== [$SERVER_NAME] installing otelcol-contrib $OTEL_VERSION (role=$ROLE, port=$PORT)"

# 1. Install package (deb/rpm autodetect), idempotent.
if ! command -v /usr/bin/otelcol-contrib >/dev/null 2>&1; then
  ARCH=$(dpkg --print-architecture 2>/dev/null || uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
  BASE="https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v${OTEL_VERSION}"
  if command -v dpkg >/dev/null 2>&1; then
    curl -fsSLO "${BASE}/otelcol-contrib_${OTEL_VERSION}_linux_${ARCH}.deb"
    dpkg -i "otelcol-contrib_${OTEL_VERSION}_linux_${ARCH}.deb"
  else
    curl -fsSLO "${BASE}/otelcol-contrib_${OTEL_VERSION}_linux_${ARCH}.rpm"
    rpm -i "otelcol-contrib_${OTEL_VERSION}_linux_${ARCH}.rpm"
  fi
fi

# 2. Config — the §5 template; only server/role/environment + port differ per host.
mkdir -p /etc/otelcol-contrib
cat > /etc/otelcol-contrib/config.yaml <<EOF
# CTMS OTel agent — ${SERVER_NAME}. Generated by install-otel-agent.sh.
extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu: {}
      load: {}
      memory: {}
      disk: {}
      network: {}
      paging: {}
      processes: {}
      filesystem:
        exclude_fs_types:
          fs_types: [autofs, binfmt_misc, cgroup, cgroup2, configfs, debugfs, devpts, devtmpfs, fusectl, hugetlbfs, mqueue, overlay, proc, procfs, pstore, securityfs, sysfs, tracefs, tmpfs]
          match_type: strict
        exclude_mount_points:
          mount_points: ["/dev/.*", "/proc/.*", "/sys/.*", "/run/.*", "/var/lib/docker/.*"]
          match_type: regexp
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318

processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resourcedetection:
    detectors: [env, system]
    system:
      hostname_sources: [os]
  resource:
    attributes:
      - key: server
        value: ${SERVER_NAME}
        action: upsert
      - key: role
        value: ${ROLE}
        action: upsert
      - key: environment
        value: production
        action: upsert
  batch:
    timeout: 10s
    send_batch_size: 8192

exporters:
  prometheus:
    endpoint: 0.0.0.0:${PORT}
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true
  otlp/traces:
    endpoint: ${TRACE_ENDPOINT}
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [otlp/traces]
EOF

/usr/bin/otelcol-contrib validate --config=/etc/otelcol-contrib/config.yaml

# 3. Start & enable.
systemctl enable --now otelcol-contrib
systemctl restart otelcol-contrib   # pick up config if service pre-existed
sleep 5
systemctl is-active otelcol-contrib

# 4. Local verify (§3 Step 1.5).
curl -sf "http://127.0.0.1:${PORT}/metrics" | grep -m3 -E '^system_(cpu|memory|filesystem)' \
  || { echo "FAIL: no system_* metrics on :${PORT}" >&2; exit 1; }
curl -sf http://127.0.0.1:13133/ >/dev/null && echo "health check OK"

echo "== [$SERVER_NAME] DONE. Now allow Server 5 through the firewall if needed:"
echo "   sudo ufw allow from ${MONITORING_IP} to any port ${PORT} proto tcp"
echo "   (Docker hosts: sudo iptables -I DOCKER-USER -p tcp --dport ${PORT} -s ${MONITORING_IP} -j ACCEPT)"
